cart/urls.py
from django.urls import path, re_path
from . import views

app_name = "cart"

urlpatterns = [
    # cart urls
    path(
        "add-product/",
        views.SessionAddProduct.as_view(),
        name="add-product",
    ),
    path(
        "cart-summary/",
        views.SessionCartSummaryView.as_view(),
        name="cart-summary",
    ),
    path(
        "update-product-quantity/",
        views.SessionUpdateProductQuantityView.as_view(),
        name="update-product-quantity",
    ),
    path(
        "cart-remove-product/",
        views.SessionRemoveProductView.as_view(),
        name="remove-product",
    ),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from shop.sitemaps import ProductSitemap
from website.sitemaps import StaticViewSitemap
from django.contrib.sitemaps.views import sitemap

# ________MAIN URLS________
sitemaps = {
    'static': StaticViewSitemap,
    'products': ProductSitemap
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls", namespace="website")),  # website app main route
    path(
        "accounts/", include("accounts.urls", namespace="accounts")
    ),  # accounts app main route
    path("shop/", include("shop.urls", namespace="shop")),  # shop app main route
    path("cart/", include("cart.urls", namespace="cart")),  # cart app main route
    path("order/", include("order.urls", namespace="order")),  # order app main route
    path(
        "dashboard/", include("dashboard.urls", namespace="dashboard")
    ),  # dashboard app main route
    path(
        "payment/", include("payment.urls", namespace="payment")
    ),  # payment app main route
    path(
        "review/", include("review.urls", namespace="review")
    ),  # review app main route


    # ______CKEDITOR_______#
    path(
        "ckeditor5/", include("django_ckeditor_5.urls"), name="ck_editor_5_upload_file"
    ),
    # __CEO Optomization__#
    # path("sitemaps.xml", include("sitemaps.urls")),
    path("robots.txt", include("robots.urls")),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name="django.contrib.sitemaps.views.sitemap"),

]

# route Debugger toolbar
if settings.SHOW_DEBUGGER_TOOLBAR:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

# loading static and media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
# 404 page
if settings.DEBUG == False:
    handler404 = 'website.views.custom_404'

shop/urls.py
from django.urls import path, re_path
from . import views

app_name = "shop"

urlpatterns = [
    # product list & retriv & delete & update
    path("product/", views.ProductGridView.as_view(), name="product-grid"),
    re_path(
        r"product/(?P<slug>[-\w]+)/detail/",
        views.ProductDetailView.as_view(),
        name="product-detail",
    ),
    path(
        "add-or-remove-wishlists/",
        views.AddOrRemoveWishlistView.as_view(),
        name="add-or-remove-wishlist",
    ),
]

templates/inc/latest-product.html
{% load static %}

<!-- Card Grid -->
<div class="container content-space-2 content-space-lg-3">
    <!-- Title -->
    <div class="w-md-75 w-lg-50 text-center mx-md-auto mb-5 mb-md-9">
        <h2>محصولات پرطرفدار</h2>
    </div>
    <!-- End Title -->

    <div class="row row-cols-sm-2 row-cols-md-3 row-cols-lg-4 mb-3">
        {% for latest_product in famous_products %}
        <div class="col mb-4">
            <!-- Card -->
            <div class="card card-bordered shadow-none text-center h-100">
                <div class="card-pinned">
                    <img loading="lazy"  class="card-img-top" src="{{latest_product.image_medium.url}}" alt="Image Description">
                    {% if latest_product.is_new and not latest_product.end_inventory %}
                                    <div class="card-pinned-top-start">
                                        <span class="badge bg-success rounded-pill">جدید</span>
                                      </div>
                    {% elif latest_product.end_inventory %}
                    <div class="card-pinned-top-start">
                        <span class="badge bg-danger rounded-pill">اتمام موجودی</span>
                        </div>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                    <div class="card-pinned-top-end">
                        <button type="button"
                            class="btn btn-outline-secondary btn-xs btn-icon rounded-circle {% if latest_product.id in wishlist_items %} active {% endif %}"
                            data-bs-toggle="tooltip" data-bs-placement="top" title="افزودن به علایق"
                            onclick="addToWishlist(this,`{{latest_product.id}}`)">
                            <i class="bi-heart"></i>
                        </button>
                    </div>
                    {% endif %}
                </div>

                <div class="card-body">
                    <div class="mb-2">
                        <a class="link-sm link-secondary" href="#"> {{latest_product.category.title}} </a>
                      
                    </div>

                    <h4 class="card-title">
                        <a class="text-dark"
                            href="{% url 'shop:product-detail' slug=latest_product.slug %}">{{latest_product.title}}</a>
                    </h4>
                    {% if latest_product.is_discount%}
                    <p class="card-text text-dark fs-4">
                        <span class="formatted-price">{{latest_product.get_price}}</span>
                        <span
                            class="text-body me-1 fs-6 formatted-price text-decoration-line-through">{{latest_product.price}}</span>
                    </p>
                    {% else %}
                    <p class="card-text text-dark fs-4 formatted-price"> {{latest_product.price}} </p>
                    {% endif %}
                </div>

                <div class="card-footer pt-0">
                    <!-- Rating -->
                    <a class="d-inline-flex align-items-center mb-3" href="#">
                        <div class="d-flex gap-1 ms-2">
                            {% for i in "12345" %}
                            {% if i|add:0 <= latest_product.avg_rate %} <span><i
                                    class="bi bi-star-fill star-rate"></i></span>
                                {% else %}
                                <span><i class="bi bi-star star-rate"></i></span>
                                {% endif %}

                                {% endfor %}
                                <span class="ms-1">{{latest_product.avg_rate}}/5</span>
                        </div>

                    </a>
                    <!-- End Rating -->

                   {% if not latest_product.end_inventory %}
                   <div class="d-grid mb-4">
                    <button type="button" class="btn btn-primary btntransition"
                            onclick="addToCart('{{ latest_product.id }}')">افزودن به سبد خرید
                    </button>
                </div>
                {%else%}
                <div class="d-grid mb-4">
                    <button type="button" class="btn btn-primary btntransition"
                            disabled>اتمام موجودی
                    </button>
                </div>
                {%endif%}

                </div>
            </div>
            <!-- End Card -->
        </div>
        {% empty %}
        <div class="row text-center w-100 py-5">
            <p class="text-center">هیچ کالایی برای نمایش وجود ندارد</p>
        </div>
        <!-- End Col -->
        {% endfor %}
    </div>
    <!-- End Row -->

    <div class="text-center">
        <a class="btn btn-outline-primary btn-transition rounded-pill" href="{% url 'shop:product-grid' %}">مشاهده تمامی
            محصولات</a>
    </div>
</div>
<!-- End Card Grid -->

templates/inc/mega_menu.html
<!-- Pages -->
<li class="hs-has-mega-menu nav-item" data-hs-mega-menu-item-options='{
  "desktop": {
    "position": "right",
    "maxWidth": "27rem"
  }
}'>
<a id="pagesMegaMenu" class="hs-mega-menu-invoker nav-link dropdown-toggle " aria-current="page" href="#"
role="button" data-bs-toggle="dropdown" aria-expanded="false">صفحات</a>

<!-- Mega Menu -->
<div class="hs-mega-menu dropdown-menu" aria-labelledby="pagesMegaMenu" style="min-width: 27rem;">
<div class="navbar-dropdown-menu-inner">
  <span class="dropdown-header">عناصر</span>

  <div class="row">
    <div class="col-sm mb-3 mb-sm-0">
      <a class="dropdown-item " href="/categories.html">دسته بندی ها</a>
    </div>
    <!-- End Col -->

    <div class="col-sm">
      <a class="dropdown-item " href="/cart.html">سبد خرید</a>
      <a class="dropdown-item " href="/order-completed.html">سفارش ها</a>
    </div>
    <!-- End Col -->
  </div>
  <!-- End Row -->
</div>

<!-- Mega Menu Banner -->
<div class="navbar-dropdown-menu-shop-banner">
  <div class="d-flex">
    <div class="flex-shrink-0">
      <img class="navbar-dropdown-menu-shop-banner-img" src="/assets/img/mockups/img4.png"
        alt="Image Description">
    </div>

    <div class="flex-grow-1 p-4">
      <span class="h4 d-block text-primary">برنده تی شرت</span>
      <p>یکی از تی شرت های برند Front ما را برنده شوید.</p>
      <a class="btn btn-sm btn-soft-primary btn-transition" href="/index.html">بیشتر بدانید <i
          class="bi-chevron-left small"></i></a>
    </div>
  </div>
</div>
<!-- End Mega Menu Banner -->
</div>
<!-- End Mega Menu -->
</li>
<!-- End Pages -->

templates/inc/similar-products.html
{% load static %}


<div class="container content-space-2 content-space-lg-3">
            <!-- Title -->
            <div class="w-md-75 w-lg-50 text-center mx-md-auto mb-5 mb-md-9">
                <h2>محصولات مشابه</h2>
            </div>
            <!-- End Title -->


    <div class="row row-cols-sm-2 row-cols-md-3 row-cols-lg-4 mb-3">
        {% for similar_product in similar_products %}
        <div class="col mb-4">
            <!-- Card -->
            <div class="card card-bordered shadow-none text-center h-100">
                <div class="card-pinned">
                    <img class="card-img-top" src="{{similar_product.image_medium.url}}" alt="Image Description">
                    {% if similar_product.is_new and not similar_product.end_inventory %}
                                    <div class="card-pinned-top-start">
                                        <span class="badge bg-success rounded-pill">جدید</span>
                                      </div>
                                    {% elif similar_product.end_inventory %}
                                    <div class="card-pinned-top-start">
                                        <span class="badge bg-danger rounded-pill">اتمام موجودی</span>
                                      </div>
                                    {% endif %}
                    {% if request.user.is_authenticated %}
                    <div class="card-pinned-top-end">
                        <button type="button"
                            class="btn btn-outline-secondary btn-xs btn-icon rounded-circle {% if similar_product.id in wishlist_items %} active {% endif %}"
                            data-bs-toggle="tooltip" data-bs-placement="top" title="افزودن به علایق"
                            onclick="addToWishlist(this,`{{similar_product.id}}`)">
                            <i class="bi-heart"></i>
                        </button>
                    </div>
                    {% endif %}
                </div>

                <div class="card-body">
                    <div class="mb-2">
                        <a class="link-sm link-secondary" href="#"> {{similar_product.category.title}} </a>
                    
                    </div>

                    <h4 class="card-title">
                        <a class="text-dark"
                            href="{% url 'shop:product-detail' slug=similar_product.slug %}">{{similar_product.title}}</a>
                    </h4>
                    {% if similar_product.is_discount %}
                                        <p class="card-text text-dark fs-4">
                                            <span class="text-body me-1 fs-6 formatted-price text-decoration-line-through">{{ similar_product.price }}</span>
                                            <span class="formatted-price">{{ similar_product.get_price }}</span>


                                        </p>
                                    {% else %}
                                        <p class="card-text text-dark fs-4">
                                            <span class=" formatted-price"> {{ similar_product.price }}</span>

                                        </p>
                                    {% endif %}
                </div>

                <div class="card-footer pt-0">
                    <!-- Rating -->
                    <a class="d-inline-flex align-items-center mb-3" href="#">
                        <div class="d-flex gap-1 ms-2">
                            {% for i in "12345" %}
                            {% if i|add:0 <= similar_product.avg_rate %} <span><i
                                    class="bi bi-star-fill star-rate"></i></span>
                                {% else %}
                                <span><i class="bi bi-star star-rate"></i></span>
                                {% endif %}

                                {% endfor %}
                                <span class="ms-1">{{similar_product.avg_rate}}/5</span>
                        </div>

                    </a>
                    <!-- End Rating -->

                    {% if not similar_product.end_inventory %}
                   <div class="d-grid mb-4">
                    <button type="button" class="btn btn-primary btntransition"
                            onclick="addToCart('{{ similar_product.id }}')">افزودن به سبد خرید
                    </button>
                </div>
                {%else%}
                <div class="d-grid mb-4">
                    <button type="button" class="btn btn-primary btntransition"
                            disabled>اتمام موجودی
                    </button>
                </div>
                {%endif%}
            </div>
        </div>
            <!-- End Card -->
        </div>
        {% empty %}
        <div class="row text-center w-100 py-5">
            <p class="text-center">هیچ کالایی برای نمایش وجود ندارد</p>
        </div>
        <!-- End Col -->
        {% endfor %}
    </div>            <!-- End Row -->
        </div>